# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: 'https'
  url: 'your_domain'
  port: null
  internal_port: '1500'

# ==========================
# CONFIG
# ==========================

hosts_config:
  http: *http_host
  grpc: null
  graphql: null

connection_config:
  is_local: false
  is_prod: true
  is_vault_real: true
  has_tls_proxy: true

db_config:
  db_type: Postgres
  url: 'heimdall-db'
  port: '5432'

wallet_config:
  api:
    protocol: 'https'
    url: 'wallet.demo.walt.id'
    port: null
  id: null

did_config:
  did: 'did:web:your_domain'
  type: Web
  did_web_options:
    domain: 'your_domain'
    path: null

role: EcoAuthority

api_config:
  version: 'v1'
  openapi_path: '/app/static/specs/openapi/openapi.json'

vc_config:
  vc_model: JwtVc
  w3c_data_model: V2

issue_config:
  ds_config:
    dataspace_id: 'change_me'
  clh_config:
    label_level: 'change_me'
    engine_version: 'change_me'
    rules_version: 'change_me'
    validated_criteria: 'change_me'

verify_req_config:
  is_cert_allowed: true
  vcs_requested: [ 'gx:VatId','gx:LegalPerson','gx:TermsAndConditions' ]

is_react: true
