# ==========================
# COMMON ANCHORS
# ==========================
http_host: &http_host
  protocol: 'http'
  url: 'host.docker.internal'
  port: '1500'
  internal_port: null

# ==========================
# CONFIG
# ==========================

hosts_config:
  http: *http_host
  grpc: null
  graphql: null

connection_config:
  is_prod: false
  is_vault_real: false
  has_tls_proxy: false

db_config:
  db_type: Postgres
  url: 'heimdall-db'
  port: '5432'

wallet_config:
  wallet: Fafnir
  api:
    http:
      protocol: 'http'
      url: 'fafnir-wallet'
      port: '7001'
    grpc: null
    graphql: null

#did_config:
#  type: Jwk

did_config:
  type: Web
  domain: 'host.docker.internal'
  path:
  port: '1500'

role: DataSpaceAuthority

api_config:
  version: 'v1'
  openapi_path: '/app/static/specs/openapi/openapi.json'

issue_config:

verify_req_config:
  is_cert_allowed: true
  auto_approve_cert: true
  vcs_requested: []
